# Generated by Django 5.2.17 on 2026-09-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=32)),
                ('iin', models.CharField(max_length=12)),
                ('amount', models.PositiveIntegerField()),
                ('term_months', models.PositiveSmallIntegerField()),
                ('monthly_payment', models.PositiveIntegerField(default=0)),
                ('total_payment', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
